# Should the bot try to link to your terminal/console for commands?
enableConsole: true

# Please copy your Discord API token here.
# If the token is set to "<none>", the bot will not load.
# If the token is invalid or discord does not allow it, the bot will not load.
apiToken: "<none>"

# This is the Discord user ID of the bot owner. This may be used for certain commands.
botOwnerId: "<none>"

# This is a list of guilds that the bot is active in.
# The list is empty until configured and the bot will not load.
guilds: []
